### ISSUE TITLE
[Feature Request] Version changing

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#102]
https://github.com/dogmike/secretlounge-ng/blob/master/config.yaml.example#L45

**Comment by Charibdys** [comment]
This feature is only applicable to developers. If you're changing the version number, you're generally doing this because you have implemented a new feature. 

Dev's can just change the `format_version` [function](https://github.com/Charibdys/Private-Parlor/blob/cc21948eaf02d7c097d8ae93246b7830daf8aaf1/src/privateparlor/format.cr#L371) to represent their version of the code.
