### ISSUE TITLE
Assign rank, unban, whitelist from bot interface

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#104]
See https://github.com/dogmike/secretlounge-ng#faq

**Comment by Charibdys** [comment]
Whitelist command is already implemented and only accessible when the bot has closed registration, see [whitelist command implementation](https://github.com/Charibdys/Private-Parlor/blob/5fd08c33b7a16f694be86208a638bf2b36da35c9/src/privateparlor/telegram.cr#L1127C49-L1127C49)

Commands for promoting and demoting user ranks already exists.

Unban command is not necessary due to its rare usecase and the fact that banned users are just users with a rank of "-10". The `/promote [username] User`, or what ever rank is not considered banned, can be used to unban a user.
