### ISSUE TITLE
user support & ban appeal in 1 bot only, i.e. the bot running private-parlor

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#106]
* **Is your feature request related to a problem? Please describe.**
Problem is telegram allows to create to 20 bots only so lets not waste token 

* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.
My approach is /support <message> command and message gets forwarded to mods private group
* **What is the motivation / use case for this feature?**
Currently no Crystal support bot exists

* **Other information** (e.g. detailed explanation, related issues, code examples)

**Comment by aicynide** [comment]
Filled the issue template @Charibdys

**Comment by Charibdys** [comment]
Ideally, you don't want someone that's banned to keep using the bot.

There are merits to compartmentalizing an anonymous chat bot from a support bot. This compartmentalization typically filters spammers and trolls, as honest users are generally more likely to spend the effort to find the support bot and make an appeal. If malicious users can appeal within the same bot they are banned from, then very little effort is required to keep being malicious (to the administrators instead of the user base).

Again on the spammers and trolls, if they're abusing the /support command, they would need to be banned twice: once from the chat bot, and once from using the /support command. It's much simpler when a ban equates to being unable to use the bot.

There are multiple solutions to this that do not require using up one of the user's bot slots. One could use that private group chat for appeals. One could also use their Telegram account and resolve appeals via PM's, or use a website, email, or Google Forms, etc.

Private Parlor is fine being just an anonymous chat bot. It need not be an anonymous chat bot and a support bot at the same time. 

There's no particular reason that a Telegram support bot needs to be implemented in Crystal, nor is there a particular need for another implementation of a support bot, as multiple solutions to that exist already.

**Comment by aicynide** [comment]
>Private Parlor is fine being just an anonymous chat bot. It need not be an anonymous chat bot and a support bot at the same time.

Ok you want this? Then make the support bot send tripcode signed message hiding their username in admins' private group, then there's no way admins will know their real telegram account like https://github.com/sfan5/tgsupportbot does, not respecting user's privacy, Problem solved and this way private-parlor will be 100% anonymous

**Comment by Charibdys** [comment]
The problem is not anonymity. The reason for not adding a support bot to Private Parlor is that Private Parlor and a support bot are two separate things that serve different purposes. There is no good reason to mix the two together into one bot; I have already explained the complications with this. 

While there are a few support bots that do not reveal the identity of the user, eventually you will have to de-anonymize the user if you want to resolve some issue about their account in the Private Parlor bot.
