### ISSUE TITLE
Let users manually clear tripcode or expire tripcode after a certain period of time

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#107]
* **Is your feature request related to a problem? Please describe.**

* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.

* **What is the motivation / use case for this feature?**

* **Other information** (e.g. detailed explanation, related issues, code examples)

**Comment by Charibdys** [comment]
Fill out the template, as a use case for this feature would be good to know.

I can't see this being a useful feature. There is no reason for the user to remove their tripcode. If the user doesn't want to use it, then he doesn't have to sign with his tripcode. If the user doesn't like his tripcode, he can set it to something else. 

Similarly, there's no reason to expire tripcodes, since a user can just use the same name and password for their new tripcode. This would serve as an inconvenience.

If using pseudonymous mode, where tripcode usage is enforced, then neither removing nor expiring tripcodes makes sense.

**Comment by aicynide** [comment]
But it expires frequently in 4chan. 
Besides I deleted whole database just to delete tripcode please re-open this request

**Comment by Charibdys** [comment]
4chan likely does not keep track of tripcodes but generates them on a per pos basis. There's no reason for them to expire as the whole point of a tripcode is to be an indentifier within a thread or across multiple threads.

As for the database, always backup before you modify it. Use a database GUI like SQLiteBrowser or DBeaver if you're not comfortable modifying your database from the command line. These GUI's typically have an undo feature in case something goes wrong.
