### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#111]
Is your feature request related to a problem? Please describe.

Current feature additions in Private-Parlor require core code modifications, leading to complexities and potential conflicts. A plugin system would provide a modular approach to extend the bot's capabilities through custom plugins without altering its core. 
There is crystal project https://getmango.app which uses plugin system https://github.com/getmango/mango-plugins

 What is the expected behavior of this feature?
      
A plugin system should allow developers to create custom plugins seamlessly, adding new functionality. Make Private-Parlor pluggable.
We can use plugin for my previous feature request like inline bot features and reverse image search.

What is the motivation / use case for this feature?
  
A plugin architecture, similar to what Userge another popular Telegram userbot project which can handle hundreds of plugins using powerful pyrogram library. Do check the project https://github.com/UsergeTeam/Userge and its different kind of plugins to get a idea about telegram bot plugin system https://github.com/UsergeTeam/Userge-Plugins

Other information (e.g., detailed explanation, related issues, code examples)
        
I also suggest considering the migration of private-parlor development to an organization, for plugins & other private-parlor related projects

**Comment by Charibdys** [comment]
Currently Private Parlor is being refactored to reduce coupling and make it easier to extend functionality. Progress is being done on branch [v1.2](https://github.com/Charibdys/Private-Parlor/tree/v1.2).

The main goal of this refactoring is to use a plugin architecture for commands and media, with hooks that enable configurable functionality (spam checking, pseudonymous mode, R9K moderation, etc).

As for using external plugins, as with Mango, this would likely add complexity to the project, and would be unnecessary due to its scope.

**Comment by aicynide** [comment]
I believe a third-party web-ui plugin willl also be possible

**Comment by aicynide** [comment]
Even a plugin to bridge lynxchan/jschan etc. with private-parlor. So users can use both web-based imageboard or telegram bot

**Comment by aicynide** [comment]
> As for using external plugins, as with Mango, this would likely add complexity to the project, and would be unnecessary due to its scope.

Check the userge bot https://github.com/UsergeTeam/Userge it supports a wide variety of plugins and it depends on server otherwise bot can handle hundreds of external plugins, see https://github.com/UsergeTeam/Userge-Plugins

**Comment by aicynide** [comment]
https://gitgud.io/LynxChan/LynxChanAddon-ForumMode
https://gitgud.io/LynxChan/LynxChanAddon-News
https://gitgud.io/LynxChan/LynxChanAddon-OrangeText
https://gitgud.io/LynxChan/LynxChanAddon-LinkFormat

**Comment by Charibdys** [comment]
Upon giving this some more thought, I do not think a plugin architecture is applicable to Private Parlor. 

This would be difficult to implement due to Crystal being compiled and the fact that we're already 5,000 lines into the project. There are options for embedding or binding to other languages like JavaScript or Ruby and calling JS or Ruby scripts from the main Crystal program, but this isn't really necessary considering how rarely commands or message handlers need to be changed. The scope of Private Parlor does not lend itself to being a Swiss Army knife application like Userge, nor does it interact with multiple APIs where plugins would make sense like in Mango.

If a Web-UI were applicable, then it is more apt for a fork or a compile option than as a plugin.

Private Parlor will be rewritten/refactored so that it will be easier to extend or add functionality, but this approach will be more modular (built in, usage is toggleable/configured) as it is now than pluggable (where functionality is added via scripts).
