### ISSUE TITLE
A plugin for external API to use PrivateParlor in Kuroba-Ex/Chance app

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#116]
* **Is your feature request related to a problem? Please describe.**
Currently there is no official api

* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.

Telegram is very resource & battery consuming, it drains battery very quickly so I don't prefer any of telegram client for long time. Let us add PrivateParlor in Kuroba-Ex app and read it in the app and also post from Kuroba-Ex

* **What is the motivation / use case for this feature?**

Plugin System 

* **Other information** (e.g. detailed explanation, related issues, code examples)

**Comment by aicynide** [comment]
I think web-ui plugin would be able to provide API  instead of separate plugin for APU

**Comment by Charibdys** [comment]
Not exactly sure what this feature would add to the project. Private Parlor is a Telegram bot. Not having, or not using, Telegram precludes you from using Private Parlor. This feature would also require modifying Kuroba-Ex so that it can display Telegram messages, which I don't intend to do, nor would it make sense because Kuroba is for imageboards, which Private Parlor is not.

A feature like this would also require the content of user messages to be exposed such that they can be read by an external service. This I will not implement, as Private Parlor is a standalone application and is not meant to be a back-end for other apps. Messages in Private Parlor are meant to be available to users of the bot and may be visible to other Telegram users; but, they are not available for the whole world to see.

A plugin system is not applicable to this feature, as this describes an entirely different application that is somehow both an anonymous relay chat on Telegram but also a back-end for an imageboard accessed via the Web.
