### ISSUE TITLE
A web-ui for management.cr would be nice

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#97]
Easy settings changing without going through server ssh

**Comment by Charibdys** [comment]
The management tool is not meant to be used frequently, and some of it's features can be automated using a cron job, or using it in daemon mode for syncing blacklists. A Web-UI would be overboard, due to the tool's limited set of features.

Similarly, a config generation tool or a Web-UI to modify the config wouldn't be necessary. The config file need not be modified frequently, and it comes with sane defaults that are suitable for most users.

Generally, it's easier, quicker, and safer to:

-  SSH into the server, edit the config file/run the management tool, and reboot the machine/bot OR
-  Modify the config file locally and rsync it to the server

...than it is to spin up a Web browser, wait for it to connect to the WebUI, click on some buttons, and have it restart your bots.

**Comment by aicynide** [comment]
web-ui isn't a bad idea. A web-ui like znc
