### ISSUE TITLE
GC Warning: Could not open /proc/stat

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#98]
Got this error in termux
Related issue https://github.com/termux/termux-app/issues/299
Thank you

**Comment by Charibdys** [comment]
Private Parlor is currently compiled for Linux desktops using x86_64 or ARM architectures. 
In theory, it is possible for it to run on Android, but this platform is not currently supported by Private Parlor, nor will it be in the future as it's more suited for running on a server.

It is possible to compile and run Crystal programs through termux; if this is your goal, this forum thread may be some help: https://forum.crystal-lang.org/t/running-crystal-on-termux/3880.

**Comment by aicynide** [comment]
Can't old phones be used like raspberry pi server?

**Comment by Charibdys** [comment]
Perhaps, but using phones as a server goes beyond the scope of this project.
If your phone runs Linux and has either a x86_64 or ARM64 architecture, then it should work. 

Otherwise, you will need to find support elsewhere for running Crystal programs in your phone, as this is not the intention of the project and I cannot provide support for it.
